#!/bin/sh /etc/rc.common

# start after bluetoothd (62)
START=64
USE_PROCD=1
PROG=/usr/bin/gbcsdpd

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -config /etc/gbcsdpd/config.toml -logtime false
    procd_set_param file /etc/gbcsdpd/config.toml
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/gbcsdpd.pid
    procd_close_instance
}
